### ISSUE TITLE
Specify database name in the connection string

### ISSUE THREAD

**Issue by Axolotlke** [teamdeeson/warden#108]
When running the server I always get the error 

> SASL Authentication failed on database 'admin' 

My local mongo DB requires authentication before use.

It seems the MongoClient is initialized without database name, making it use the admin database that is not accesible.
See:
https://github.com/doctrine/DoctrineMongoDBBundle/issues/154
http://php.net/manual/en/mongo.connecting.auth.php (By default, the driver will authenticate against the admin database.)

This can be fixed by adding the database name to the connection string in config.yml :
```
doctrine_mongodb:
    connections:
        default:
            server: mongodb://%db_host%:%db_port%/%db_name%
```
Another way is by adding "db" to the connection options:
```
            options:
                username: %db_username%
                password: %db_password%
                db: %db_name%
```
