### ISSUE TITLE
Public Private key pair is not being generated

### ISSUE THREAD

**Issue by artursv** [teamdeeson/warden#88]
Attempting to register a Drupal site in my Warden installation fails with the following error messages:

`Exception: Unable to communicate with Warden in WardenAPI->request() (line 205 of /var/www/mysite/current/sites/all/modules/warden/warden_api.inc).`

`https://warden.stage/public-key : 500 : Internal Server Error`

Accessing https://warden.stage/public-key directly produces the following error message:

`Ouch, something broke. Please send us an email and let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.` 

As I understand from the documentation Warden should generate public and private keys at some point but apparently it`s not happening. I have tried giving www user full permissions to the folder where the keys should reside but still no luck.

Any advice would be appreciated.
A.

**Comment by mikeddeeson** [comment]
Hi @artursv,

This sounds like the installation of Warden server hasn't been completed correctly. Did you run the Warden server installation which would generate the keys? 

Could you please have a look at the logs (both PHP and Warden logs) to see if you get any errors detailed here?

Thanks
Mike

**Comment by artursv** [comment]
Hi @mikeddeeson,

Thanks for the quick reply. PHP logs contained the following:
`2017/01/18 11:17:15 [error] 2270#2270: *584 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(~/key.public): failed to open stream: No such file or directory in /var/www/warden.stage/warden/src/Deeson/WardenBundle/Services/SSLEncryptionService.php on line 75" while reading response header from upstream, client: xx.xxx.xx.xx, server: warden.stage, request: "GET /public-key HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "warden.stage"`

**Comment by mikeddeeson** [comment]
Hi @artursv,

Thanks for the log info. It looks like you are using the value for the location of the public keys to be within your users home directory (~/key.public), which the Warden server application won't have access to.

Can you update the `app/config/parameters.yml` file (which is generated by the installation) and update the `public_key_file` and `private_key_file` properties and change the directory to be full path of the `app/config` directory within your Warden server install (e.g. change ~/key.public to be /var/www/warden.stage/app/config/key.pubilc).

The server application should then regenerate the files if they don't exist.

Looking at the default setup it sets these key files to be at `~/key.public` which won't work as a default, so I'll have a look at updating this.

Thanks
Mike

**Comment by artursv** [comment]
Hi @mikeddeeson 

I updated the parameters.yml and for a good measure reinstalled the application but the keys are not there.

My parameters.yml file:

```
# This file is auto-generated during the composer install
parameters:
    locale: en
    secret: supersecret
    protocol: https
    public_key_file: /var/www/warden.stage/warden/app/config/key.public
    private_key_file: /var/www/warden.stage/warden/app/config/key.private
```

PHP produces the following:
`2017/01/18 12:43:25 [error] 3714#3714: *327 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/var/www/warden.stage/warden/app/config
/key.public): failed to open stream: No such file or directory in /var/www/warden.stage/warden/src/Deeson/WardenBundle/Services/SSLEncryptionService.php on line 75" while reading response header from upstream, client: xx.xxx.xx.xx, server: warden.stage, request: "GET /public-key HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "warden.stage"
`

 Is there something wrong with my server configuration? The application generates caches and sessions variable and whatnot just fine but these key files still seem to be an issue.

A.

**Comment by artursv** [comment]
Ok, looks like I finally managed to make it work. I ended up wrapping the path to public_key_file in quotation marks and it worked.
So my final working parameters.yml is as follows:
```
# This file is auto-generated during the composer install
parameters:
    locale: en
    secret: aCsTnss8YMAPzU6COnaYKFcr7BTiir
    protocol: https
    public_key_file: "/var/www/warden.stage/warden/app/config/key.public"
    private_key_file: "/var/www/warden.stage/warden/app/config/key.private"
```
